name: validate
on: push
jobs:
  validate-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: validate file
        run: test -f src/components/navBar/index.js
      - name: validate js file
        run: node --check src/components/navBar/index.js
